angular.module("app").directive("menu", function(){
	function linkFunc(scope, elem, attrs){
		$("#options").click(function(){
			$(".optionDisp").slideDown(200);
			$("#contactCont").slideUp(20);
			$("#infoCont").slideUp(20);
		});
		$("#contact").click(function(){
			$("#contactCont").slideDown(200);
			$(".optionDisp").slideUp(20);
			$("#infoCont").slideUp(20);
		});
		$("#info").click(function(){
			$("#infoCont").slideDown(200);
			$(".optionDisp").slideUp(20);
			$("#contactCont").slideUp(20);
		});
		$("#mainNav").mouseleave(function(){
			$(".optionDisp").slideUp('fast');
			$("#contactCont").slideUp('fast');
			$("#infoCont").slideUp('fast');
		});
		$("#rainBtn").click(function(){
			$(this).addClass('active');
			$("#whiteBtn").removeClass('active');
			$("#pinkBtn").removeClass('active');
			$("#white").slideUp(10);
			$("#pink").slideUp(10);
			$("#rain").slideDown(200);
		});
		$("#whiteBtn").click(function(){
			$(this).addClass('active');
			$("#rainBtn").removeClass('active');
			$("#pinkBtn").removeClass('active');
			$("#rain").slideUp(10);
			$("#pink").slideUp(10);
			$("#white").slideDown(300);
		});
		$("#pinkBtn").click(function(){
			$(this).addClass('active');
			$("#rainBtn").removeClass('active');
			$("#whiteBtn").removeClass('active');
			$("#rain").slideUp(10);
			$("#white").slideUp(10);
			$("#pink").slideDown(300);
		});
		$("#nCage").click(function(){
			$('body').toggleClass('cageify');
		});
	}
	return{
		templateUrl: "../views/menu.html",
		link: linkFunc
	};
});
